### ISSUE TITLE
Error while loading Project

### ISSUE THREAD

**Issue by SarthakShetty** [ksameersrk/EGM-FrontEnd#11]
Cannot load settings from file '/home/sarthak/github/EGM-FrontEnd/.idea/misc.xml': Error on line 40: The content of elements must consist of well-formed character data or markup.
Please correct the file content
Anyone knows what this is about?

**Comment by ksameersrk** [comment]
I don't know.  Like it was running in my laptop like building properly.

I am in hometown, I wont be able to check till tomorrow

**Comment by SarthakShetty** [comment]
Never mind, worked now.
Still not sure what happened then.
